version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: twitter
      MYSQL_DATABASE: twitter
    ports:
      - '3306:3306'
    volumes:
      - ./server/database:/var/lib/mysql